import java.io.File

/*** [Bitmap](https://web.maths.unsw.edu.au/~lafaye/CCM/video/format-bmp.html) */
class Bitmap(bmp: File) {
    init {
        val stream = bmp.inputStream()

        println("------- FILE HEADER ---------")
        println("Sign ${Char(stream.read())}${Char(stream.read())}")
        println("length1 ${stream.read()}")
        println("length2 ${stream.read()}")
        println("length3 ${stream.read()}")
        println("length4 ${stream.read()}")
        println("reserved1 ${stream.read()}")
        println("reserved2 ${stream.read()}")
        println("reserved3 ${stream.read()}")
        println("reserved4 ${stream.read()}")
        println("offset1 ${stream.read()}")
        println("offset2 ${stream.read()}")
        println("offset3 ${stream.read()}")
        println("offset4 ${stream.read()}")

        println("------- IMAGE HEADER ---------")
        println("header1 ${stream.read()}")
        println("header2 ${stream.read()}")
        println("header3 ${stream.read()}")
        println("header4 ${stream.read()}")
        println("width1 ${stream.read()}")
        println("width2 ${stream.read()}")
        println("width3 ${stream.read()}")
        println("width4 ${stream.read()}")
        println("height1 ${stream.read()}")
        println("height2 ${stream.read()}")
        println("height3 ${stream.read()}")
        println("height4 ${stream.read()}")
        println("plans1 ${stream.read()}")
        println("plans2 ${stream.read()}")
        println("color size1 ${stream.read()}")
        println("color size2 ${stream.read()}")
        println("compression1 ${stream.read()}")
        println("compression2 ${stream.read()}")
        println("compression3 ${stream.read()}")
        println("compression4 ${stream.read()}")
        println("img size1 ${stream.read()}")
        println("img size2 ${stream.read()}")
        println("img size3 ${stream.read()}")
        println("img size4 ${stream.read()}")
        println("resH1 ${stream.read()}")
        println("resH2 ${stream.read()}")
        println("resH3 ${stream.read()}")
        println("resH4 ${stream.read()}")
        println("resV1 ${stream.read()}")
        println("resV2 ${stream.read()}")
        println("resV3 ${stream.read()}")
        println("resV4 ${stream.read()}")
        println("colors1 ${stream.read()}")
        println("colors2 ${stream.read()}")
        println("colors3 ${stream.read()}")
        println("colors4 ${stream.read()}")
        println("!colors1 ${stream.read()}")
        println("!colors2 ${stream.read()}")
        println("!colors3 ${stream.read()}")
        println("!colors4 ${stream.read()}")
    }
}